# Generated by Django 4.2.7 on 2023-12-05 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_chat_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f67c691b-934a-11ee-88ca-581cf840cf2d')),
        ),
    ]
