# Generated by Django 4.2.7 on 2023-12-05 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_myuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0205b5c0-8fc7-4cae-8848-39756eaad5c2')),
        ),
    ]
