# Generated by Django 4.2.7 on 2023-12-05 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_myuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f0159a5a-0325-4241-af1f-70ca0ffc7e93'), unique=True),
        ),
    ]
